### PR TITLE
Refactor error handling to display team-related errors exclusively in…

### PR DESCRIPTION
**Pull request by jamesadelhelm**
… the team column 

Errors messages such as Failed to Add Team Member when the user adds a username that does not exist used to display in both the team column and the bottom of the page. Now the error message displays only in the team column.

### CODE REVIEW

**Comment by GPropersi** [comment]
Tried adding a team with same name, got an error message at the bottom. Is this the message you're referring to?-

image

**Comment by adelhelj** [comment]
Previously the error message for failed to add team member would display there, where you're seeing the error message, and also in the team column (where it solely displays now). In other words, there were two error messages displayed, and this changes it so there is just the 1 error message in the team column when there is failure to add team member.

**Comment by GPropersi** [comment]
Got it - would moving the other one over (one I showed) to the same place make sense?

**Comment by adelhelj** [comment]
Yep, I'll incorporate that!

**Review by GPropersi — APPROVED** [review]
LGTM!

**Pull request merged**
